name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: jiangsongyang/jiangsongyang@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          COMMIT_BY_ME: 'False'
          SHOW_DAYS_OF_WEEK: 'False'
          SHOW_OS: 'False'
          SHOW_TIMEZONE: 'False'
          SHOW_EDITORS: 'False'
          SHOW_LANGUAGE_PER_REPO: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_LOC_CHART: 'False'
          SHOW_COMMIT: 'True'
          SHOW_LANGUAGE: 'True'
          SHOW_PROJECTS: 'False'
          INPUT_SHOW_TOTAL_CODE_TIME: 'False'
